name: Build Examples

on:
    # trigger on git push
    push:
        paths:
            - "projects/**"
            - ".github/workflows/build-examples.yml" # might not need this
    # trigger manually
    workflow_dispatch:

jobs:
    build-example:
        name: Build Example
        runs-on: ubuntu-latest
        env:
            CI: false # might not need this. this refers to react ui related things.
        strategy:
            # build all examples independently
            fail-fast: false
            matrix:
                project: ["tradeable-cashflow", "borrow-against-salary", "instant-distribution-intro", "money-streaming-intro/money-streaming-intro-hardhat", "money-streaming-intro/money-streaming-intro-foundry"]
                install: ["clean-install"]
                node-version: [16]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install, Build, and Test
              run: |
                  cd "projects/${{ matrix.project }}"
                  yarn install
                  yarn build
                  yarn test
